language: java
sudo: false

install:
  - 

matrix:
  fast_finish: true
  include:
    

    # NoErrorTest - Orekit (oraclejdk8)
    - os: osx
      jdk: oraclejdk8
      env:
        - DESC="NoErrorTest - Orekit"
        - CMD1="mvn clean install -DskipTests -DskipITs -Dcobertura.skip=true "
        - CMD2="              -Dpmd.skip=true -Dfindbugs.skip=true "
        - CMD3="              -Dcheckstyle.ant.skip=true -Dcheckstyle.skip=true"
        - CMD4=" && git clone https://github.com/checkstyle/Orekit.git && cd Orekit"
        - CMD5=" && sed -i '' 's/<orekit\.checkstyle\.version>6\.6</<orekit.checkstyle.version>"
        - CMD6="$(mvn -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec)</"
        - CMD7="' pom.xml "
        - CMD8=" && mvn compile checkstyle:check"
        - CMD=$CMD1$CMD2$CMD3$CMD4$CMD5$CMD6$CMD7$CMD8
        - COVERAGE_CMD=""

    # NoExceptiontest - Checkstyle, sevntu-checkstyle (oraclejdk8)
    - os: osx
      jdk: oraclejdk8
      env:
        - DESC="NoExceptionTest - Checkstyle, sevntu-checkstyle"
        - CMD1="git clone https://github.com/checkstyle/contribution && cd contribution/checkstyle-tester "
        - CMD2=" && sed -i '' 's/^guava/#guava/' projects-for-travis.properties "
        - CMD3=" && sed -i '' 's/#checkstyle/checkstyle/' projects-for-travis.properties "
        - CMD4=" && sed -i '' 's/#sevntu-checkstyle/sevntu-checkstyle/' projects-for-travis.properties "
        - CMD5=" && sed -i '' 's/projects-to-test-on.properties/projects-for-travis.properties/' launch.sh "
        - CMD6=" && cd ../../ && mvn clean install -DskipTests -DskipITs -Dcobertura.skip=true "
        - CMD7="                  -Dpmd.skip=true -Dfindbugs.skip=true "
        - CMD8="                  -Dcheckstyle.ant.skip=true -Dcheckstyle.skip=true "
        - CMD9=" && cd contribution/checkstyle-tester "
        - CMD10=" && ./launch.sh -Dcheckstyle.config.location=checks-nonjavadoc-error.xml"
        - CMD=$CMD1$CMD2$CMD3$CMD4$CMD5$CMD6$CMD7$CMD8$CMD9$CMD10
        - COVERAGE_CMD=""
    # NoExceptiontest - Guava (oraclejdk8)
    - os: osx
      jdk: oraclejdk8
      env:
        - DESC="NoExceptionTest - Guava"
        - CMD1="git clone https://github.com/checkstyle/contribution && cd contribution/checkstyle-tester"
        - CMD2=" && sed -i '' 's/^guava/#guava/' projects-for-travis.properties"
        - CMD3=" && sed -i '' 's/#guava/guava/' projects-for-travis.properties"
        - CMD4=" && sed -i '' 's/projects-to-test-on.properties/projects-for-travis.properties/' launch.sh"
        - CMD5=" && cd ../../ && mvn clean install -DskipTests -DskipITs -Dcobertura.skip=true"
        - CMD6="                   -Dpmd.skip=true -Dfindbugs.skip=true "
        - CMD7="                   -Dcheckstyle.ant.skip=true -Dcheckstyle.skip=true "
        - CMD8=" && cd contribution/checkstyle-tester "
        - CMD9=" && ./launch.sh -Dcheckstyle.config.location=checks-nonjavadoc-error.xml"
        - CMD=$CMD1$CMD2$CMD3$CMD4$CMD5$CMD6$CMD7$CMD8$CMD9
        - COVERAGE_CMD=""
    # NoExceptionTest - Hibernate ORM (oraclejdk8)
    - os: osx
      jdk: oraclejdk8
      env:
        - DESC="NoExceptionTest - Hibernate ORM"
        - CMD1="git clone https://github.com/checkstyle/contribution && cd contribution/checkstyle-tester "
        - CMD2="&& sed -i '' 's/^guava/#guava/' projects-for-travis.properties "
        - CMD3="&& sed -i '' 's/#hibernate-orm/hibernate-orm/' projects-for-travis.properties "
        - CMD4="&& sed -i '' 's/projects-to-test-on.properties/projects-for-travis.properties/' launch.sh "
        - CMD5="&& cd ../../ && mvn clean install -DskipTests -DskipITs -Dcobertura.skip=true "
        - CMD6="                  -Dpmd.skip=true -Dfindbugs.skip=true "
        - CMD7="                  -Dcheckstyle.ant.skip=true -Dcheckstyle.skip=true "
        - CMD8="&& cd contribution/checkstyle-tester "
        - CMD9="&& ./launch.sh -Dcheckstyle.config.location=checks-nonjavadoc-error.xml"
        - CMD=$CMD1$CMD2$CMD3$CMD4$CMD5$CMD6$CMD7$CMD8$CMD9
        - COVERAGE_CMD=""
    # NoExceptionTest - FindBugs (oraclejdk8)
    - os: osx
      jdk: oraclejdk8
      env:
        - DESC="NoExceptionTest - FindBugs"
        - CMD1="git clone https://github.com/checkstyle/contribution && cd contribution/checkstyle-tester "
        - CMD2="&& sed -i '' 's/^guava/#guava/' projects-for-travis.properties "
        - CMD3="&& sed -i '' 's/#findbugs/findbugs/' projects-for-travis.properties "
        - CMD4="&& sed -i '' 's/projects-to-test-on.properties/projects-for-travis.properties/' launch.sh "
        - CMD5="&& cd ../../ && mvn clean install -DskipTests -DskipITs -Dcobertura.skip=true "
        - CMD6="                  -Dpmd.skip=true -Dfindbugs.skip=true "
        - CMD7="                  -Dcheckstyle.ant.skip=true -Dcheckstyle.skip=true "
        - CMD8="&& cd contribution/checkstyle-tester "
        - CMD9="&& ./launch.sh -Dcheckstyle.config.location=checks-nonjavadoc-error.xml"
        - CMD=$CMD1$CMD2$CMD3$CMD4$CMD5$CMD6$CMD7$CMD8$CMD9
        - COVERAGE_CMD=""
    # NoExceptionTest - Pmd,elasticsearch,lombok-ast (oraclejdk8)
    - os: osx
      jdk: oraclejdk8
      env:
        - DESC="NoExceptionTest - Pmd,elasticsearch,lombok-ast"
        - CMD1="git clone https://github.com/checkstyle/contribution && cd contribution/checkstyle-tester "
        - CMD2="&& sed -i '' 's/^guava/#guava/' projects-for-travis.properties "
        - CMD3="&& sed -i '' 's/#pmd/pmd/' projects-for-travis.properties "
        - CMD4="&& sed -i '' 's/#elasticsearch/elasticsearch/' projects-for-travis.properties "
        - CMD5="&& sed -i '' 's/#lombok-ast/lombok-ast/' projects-for-travis.properties "
        - CMD6="&& sed -i '' 's/projects-to-test-on.properties/projects-for-travis.properties/' launch.sh "
        - CMD7="&& cd ../../ && mvn clean install -DskipTests -DskipITs -Dcobertura.skip=true "
        - CMD8="                  -Dpmd.skip=true -Dfindbugs.skip=true "
        - CMD9="                  -Dcheckstyle.ant.skip=true -Dcheckstyle.skip=true "
        - CMD10="&& cd contribution/checkstyle-tester "
        - CMD11="&& ./launch.sh -Dcheckstyle.config.location=checks-nonjavadoc-error.xml"
        - CMD=$CMD1$CMD2$CMD3$CMD4$CMD5$CMD6$CMD7$CMD8$CMD9$CMD10$CMD11
        - COVERAGE_CMD=""
    # NoExceptionTest - RxJava,java-design-patterns,MaterialDesignLibrary,apache-ant,apache-jsecurity,android-launcher (oraclejdk8)
    - os: osx
      jdk: oraclejdk8
      env:
        - DESC="NoExceptionTest - RxJava,java-design-patterns,MaterialDesignLibrary,apache-ant,apache-jsecurity,android-launcher"
        - CMD01="git clone https://github.com/checkstyle/contribution && cd contribution/checkstyle-tester "
        - CMD02="&& sed -i '' 's/^guava/#guava/' projects-for-travis.properties "
        - CMD03="&& sed -i '' 's/#RxJava/RxJava/' projects-for-travis.properties "
        - CMD04="&& sed -i '' 's/#java-design-patterns/java-design-patterns/' projects-for-travis.properties "
        - CMD05="&& sed -i '' 's/#MaterialDesignLibrary/MaterialDesignLibrary/' projects-for-travis.properties "
        - CMD06="&& sed -i '' 's/#apache-ant/apache-ant/' projects-for-travis.properties "
        - CMD07="&& sed -i '' 's/#apache-jsecurity/apache-jsecurity/' projects-for-travis.properties "
        - CMD08="&& sed -i '' 's/#android-launcher/android-launcher/' projects-for-travis.properties "
        - CMD09="&& sed -i '' 's/projects-to-test-on.properties/projects-for-travis.properties/' launch.sh "
        - CMD10="&& cd ../../ && mvn clean install -DskipTests -DskipITs -Dcobertura.skip=true "
        - CMD11="                  -Dpmd.skip=true -Dfindbugs.skip=true "
        - CMD12="                  -Dcheckstyle.ant.skip=true -Dcheckstyle.skip=true "
        - CMD13="&& cd contribution/checkstyle-tester "
        - CMD14="&& ./launch.sh -Dcheckstyle.config.location=checks-nonjavadoc-error.xml"
        - CMD=$CMD01$CMD02$CMD03$CMD04$CMD05$CMD06$CMD07$CMD08$CMD09$CMD10$CMD11$CMD12$CMD13$CMD14
        - COVERAGE_CMD=""
    # NoExceptionTest - Spring (oraclejdk8)
    - os: osx
      jdk: oraclejdk8
      env:
        - DESC="NoExceptionTest - Spring"
        - CMD1="git clone https://github.com/checkstyle/contribution && cd contribution/checkstyle-tester"
        - CMD2=" && sed -i '' 's/^guava/#guava/' projects-for-travis.properties "
        - CMD3=" && sed -i '' 's/#spring-framework/spring-framework/' projects-for-travis.properties "
        - CMD4=" && sed -i '' 's/projects-to-test-on.properties/projects-for-travis.properties/' launch.sh "
        - CMD5=" && cd ../../ && mvn clean install -DskipTests -DskipITs -Dcobertura.skip=true "
        - CMD6="                   -Dpmd.skip=true -Dfindbugs.skip=true "
        - CMD7="                   -Dcheckstyle.ant.skip=true -Dcheckstyle.skip=true "
        - CMD8=" && cd contribution/checkstyle-tester "
        - CMD9=" && ./launch.sh -Dcheckstyle.config.location=checks-nonjavadoc-error.xml"
        - CMD=$CMD1$CMD2$CMD3$CMD4$CMD5$CMD6$CMD7$CMD8$CMD9
        - COVERAGE_CMD=""
    # NoExceptionTest - Hbase (oraclejdk8)
    - os: osx
      jdk: oraclejdk8
      env:
        - DESC="NoExceptionTest - Hbase"
        - CMD1="git clone https://github.com/checkstyle/contribution && cd contribution/checkstyle-tester "
        - CMD2="&& sed -i '' 's/^guava/#guava/' projects-for-travis.properties "
        - CMD3="&& sed -i '' 's/#Hbase/Hbase/' projects-for-travis.properties "
        - CMD4="&& sed -i '' 's/projects-to-test-on.properties/projects-for-travis.properties/' launch.sh "
        - CMD5="&& cd ../../ && mvn clean install -DskipTests -DskipITs -Dcobertura.skip=true "
        - CMD6="                 -Dpmd.skip=true -Dfindbugs.skip=true "
        - CMD7="                 -Dcheckstyle.ant.skip=true -Dcheckstyle.skip=true "
        - CMD8="&& cd contribution/checkstyle-tester "
        - CMD9="&& ./launch.sh -Dcheckstyle.config.location=checks-nonjavadoc-error.xml"
        - CMD=$CMD1$CMD2$CMD3$CMD4$CMD5$CMD6$CMD7$CMD8$CMD9
        - COVERAGE_CMD=""
    

    # MacOS verify (till cache is not working, we can not do verify)
    - os: osx
      env:
        - DESC="MacOS tests only"
        - CMD="export JAVA_HOME=$(/usr/libexec/java_home) && mvn clean integration-test failsafe:verify "
        - COVERAGE_CMD=""

    # Releasenotes generation - validaton
    - jdk: oraclejdk8
      env:
        - DESC="Releasenotes generation"
        - CMD0="if [[ $TRAVIS_PULL_REQUEST =~ ^([0-9]*)$ ]]; then exit 0; fi "
        - CMD1=" && git clone https://github.com/checkstyle/contribution && cd contribution/releasenotes-xdoc-builder "
        - CMD2=" && mvn clean compile package "
        - CMD3=" && cd ../../ && git clone https://github.com/checkstyle/checkstyle && cd checkstyle "
        - CMD4=" && LATEST_RELEASE_TAG=\$(git describe \$(git rev-list --tags --max-count=1)) && cd ../"
        - CMD5=" && CS_RELEASE_VERSION=$(mvn -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec | sed 's/-SNAPSHOT//' ) "
        - CMD6=" && echo LATEST_RELEASE_TAG=\$LATEST_RELEASE_TAG && echo CS_RELEASE_VERSION=\$CS_RELEASE_VERSION "
        - CMD7=" && java -jar contribution/releasenotes-xdoc-builder/target/releasenotes-xdoc-builder-1.0-all.jar "
        - CMD8="        -localRepoPath checkstyle -startRef \$LATEST_RELEASE_TAG -releaseNumber \$CS_RELEASE_VERSION -authToken $GITHUB_AUTH_TOKEN"
        - CMD9=" && cat releasenotes.xml "
        - CMD=$CMD0$CMD1$CMD2$CMD3$CMD4$CMD5$CMD6$CMD7$CMD8$CMD9
        - COVERAGE_CMD=""

script: eval $CMD

after_success:
  - eval $COVERAGE_CMD
  - >-
    if [[ $TRAVIS_REPO_SLUG == 'checkstyle/checkstyle'
            && $TRAVIS_BRANCH == 'master'
            && $TRAVIS_PULL_REQUEST == 'false'
            && $DEPLOY == 'true'
       ]];
    then
        mvn -s config/deploy-settings.xml deploy \
          -DskipTests -DskipITs -Dpmd.skip=true -Dfindbugs.skip=true \
          -Dcobertura.skip=true -Dcheckstyle.ant.skip=true -Dcheckstyle.skip=true ;
    fi

cache:
  directories:
  - ~/.m2

branches:
  only:
    - iss2729_uglyButWorks 
      
